main: lewbr\planpvp\PlanPvP
api: 2.0.0
load: STARTUP
name: PlanPvP
version: 1.0 [INDEV]
author: @Lew_Br

commands:
  planpvp:
    description: "Entre ou saia do minigame"
    permission: planpvp.cmd

permissions:
  planpvp.cmd:
    default: true
    description: "Todos usarem o comando do jogo"
